#!/usr/bin/env bash

#  generic build script, for building components (all of them)
#
#	Copyright (C) 2014, 2015, 2020, 2021 Leah Rowe <info@minifree.org>
#	Copyright (C) 2015 Patrick "P. J." McDermott <pj@pehjota.net>
#	Copyright (C) 2015, 2016 Klemens Nanni <contact@autoboot.org>
#	Copyright (C) 2022, Caleb La Grange <thonkpeasant@protonmail.com>
#
#	This program is free software: you can redistribute it and/or modify
#	it under the terms of the GNU General Public License as published by
#	the Free Software Foundation, either version 3 of the License, or
#	(at your option) any later version.
#
#	This program is distributed in the hope that it will be useful,
#	but WITHOUT ANY WARRANTY; without even the implied warranty of
#	MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#	GNU General Public License for more details.
#
#	You should have received a copy of the GNU General Public License
#	along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
./.gitcheck

[ "x${DEBUG+set}" = 'xset' ] && set -v
set -u -e

projectname="$(cat projectname)"

build=./resources/scripts/build

list_tasks() {
	for task in "${build}"/*; do
		printf '%s\n' "${task##*/}"
	done
}

# Takes exactly one task as parameter
list_packages() {
	for package in "${build}"/"${1}"/*; do
		printf '%s\n' "${package##*/}"
	done
}

help() {
	cat <<- EOF
	USAGE:	./build <TASK> <PACKAGE>

	possible values for 'task':
	$(list_tasks)

	Example:	./build module all
	Example:	./build module flashrom [static]
	Example:	./build roms withgrub
	Example:	./build clean all

	Refer to the ${projectname} documentation for more information.
	EOF
}

die() {
	printf 'Error: %s\n' "${@}" 1>&2
	exit 1
}

if [ $# -lt 1 ]; then
	die "Wrong number of arguments specified. See './build help'."
fi

task="${1}"

if [ "${task}" != "dependencies" ]; then
	./resources/scripts/misc/versioncheck
fi

[ "${task}" = help ] && help && exit 0

if [ $# -gt 1 ]; then

	package="${2}"
	shift 2

	case "${package}" in
		list)
			printf "Available packages for task '%s':\n\n" "${task}"
			list_packages "${task}"
			;;
		all)
			for package in $(list_packages "${task}"); do
				"${build}"/"${task}"/"${package}" $@
			done
			;;
		*)
			if [ -d "${build}"/"${task}"/ ]; then
				if [ -f "${build}"/"${task}"/"${package}" ]; then
					"${build}"/"${task}"/"${package}" $@
				else
					help
					die "Invalid package for '${task}'." \
					    " See './build ${task} list'."
				fi
			else
				help
				die "Invalid task '${task}'." \
				    " See './build help'."
			fi
	esac
else
	help
	exit 0
fi

./.gitcheck clean
