#!/usr/bin/env bash

#  generic scripts for modifying configs and such
#
#	Copyright (C) 2014, 2015, 2020, 2021 Leah Rowe <info@minifree.org>
#	Copyright (C) 2015 Patrick "P. J." McDermott <pj@pehjota.net>
#	Copyright (C) 2015, 2016 Klemens Nanni <contact@autoboot.org>
#
#    This program is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, either version 3 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with this program.  If not, see <http://www.gnu.org/licenses/>.
#

[ "x${DEBUG+set}" = 'xset' ] && set -v
set -u -e

projectname="$(cat projectname)"
./resources/scripts/misc/versioncheck

modify=./resources/scripts/modify

list_packages() {
	for package in "${modify}"/*; do
		printf '%s\n' "${package##*/}"
	done
}

# Takes exactly one package as parameter
listoptions() {
	for option in "${modify}"/"${1}"/*; do
		printf '%s\n' "${option##*/}"
	done
}

help() {
	cat <<- EOF
	USAGE:	./modify <PACKAGE> <OPTION>

	possible values for 'package':
	$(list_packages)

	Example:	./modify coreboot configs
	Example:	./modify coreboot configs x60

	Refer to the ${projectname} documentation for more information.
	EOF
}

die() {
	printf 'Error: %s\n' "${@}" 1>&2
	exit 1
}

if [ $# -lt 1 ]; then
	die "Wrong number of arguments specified. See './modify help'."
fi

package="${1}"

[ "${package}" = help ] && help && exit 0

if [ $# -gt 1 ]; then

	option="${2}"
	shift 2

	case "${option}" in
	list)
		printf "Available options for package '%s':\n\n" "${package}"
		listoptions "${package}"
		;;
	all)
		for option in $(listoptions "${package}"); do
			"${modify}"/"${package}"/"${option}" $@
		done
		;;
	*)
		if [ -d "${modify}"/"${package}"/ ]; then
			if [ -f "${modify}"/"${package}"/"${option}" ]; then
				"${modify}"/"${package}"/"${option}" $@
			else
				help
				die "Invalid option for '${package}'." \
				    " See './modify ${package} list'."
			fi
		else
			help
			die "Invalid package '${package}'. See './modify help'."
		fi
	esac
else
	help
	exit 0
fi
