;;; Copyright © 2026 Denis 'GNUtoo' Carikli <GNUtoo@cyberdimension.org>
;;;
;;; GNU Boot is free software; you can redistribute it and/or modify
;;; it under the terms of the GNU General Public License as published
;;; by the Free Software Foundation; either version 3 of the License,
;;; or (at your option) any later version.
;;;
;;; GNU Boot is distributed in the hope that it will be useful, but
;;; WITHOUT ANY WARRANTY; without even the implied warranty of
;;; MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
;;; General Public License for more details.
;;;
;;; You should have received a copy of the GNU General Public License
;;; along with Haunt.  If not, see <http://www.gnu.org/licenses/>.

(define-module (modules web-components)
  ;; Local modules
  #:export (make-lbssg-navbar))

(fluid-set! %default-port-encoding "UTF-8")

(define (_ s) s)

(define (make-lbssg-navbar post)
  `(list
    (div
     (@ (class "title"))
     (h1
      (@ (class "title"))
      ,(post-ref post 'title)))
    (div (@ (class "menu"))
         (ul
          (li (a (@ (href "/software/gnuboot/index.html"))
                 "Home"))
          (li (a (@ (href "/software/gnuboot/status.html"))
                 "Status"))
          (li (a (@ (href "/software/gnuboot/docs/install/"))
                 "Get GNU Boot"))
          (li (a (@ (href "/software/gnuboot/docs/"))
                 "Docs"))
          (li (a (@ (href "/software/gnuboot/news.html"))
                 "News"))
          (li (a (@ (href "https://savannah.gnu.org/bugs/?group=gnuboot"))
                 "Bugs"))
          (li (a (@ (href "https://savannah.gnu.org/projects/gnuboot/"))
                 "Savannah forge"))
          (li (a (@ (href "/software/gnuboot/contribute.html"))
                 "Helping GNU Boot"))
          (li (a (@ (href "/software/gnuboot/events/index.html"))
                 "Events"))
          (li (a (@ (href "/software/gnuboot/contact.html"))
                 "Contact"))))
    ;; TODO: Only kept to minimize the diff with lbssg. The
    ;; generated HTML isn't identic to lbssg, so the version
    ;; generated by lbssg is fixed by
    ;; build/lbssg/fixup-comments.sh
    (!-- (@ (class "menu")) "")
    (hr)))
