#!/usr/bin/env bash
#
# Copyright (C) 2023,2024 Denis 'GNUtoo' Carikli <GNUtoo@cyberdimension.org>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

set -e

fail()
{
    # shellcheck disable=SC2124
    message="$@"

    printf "[ !! ] scripts/checkpatch.scm test failed: %s\n" \
           "${message}"

    exit 1
}

################################################################################
# Setup                                                                        #
################################################################################

printf "+--------------------------------------+\n"
printf "| Running scripts/checkpatch.scm test: |\n"
printf "+--------------------------------------+\n"

topdir="$(dirname "$(dirname "$(realpath "$0")")")"
tmpdir="$(mktemp -d)"

test -f "${topdir}"/scripts/checkpatch.scm || fail "checkpatch.scm not found."
test -f "${topdir}"/resources/wrapper/git || \
    fail "resources/wrapper/git not found."

################################################################################
# Test if checkpatch.scm correctly finds non-aligned nodes.                    #
################################################################################

# This checks the "Add a minimal GNU Boot manual." patch which adds
# unaligned nodes.
./scripts/checkpatch.scm \
    "$(git format-patch -1 08b9e449e94e99c0ec924e2026dc650b63ddc3e5)" > \
    "${tmpdir}"/checkpatch-test-unaligned-nodes-patch.log 2>/dev/null || \
    fail "checkpatch.scm failed " \
         "when trying to detect unaligned node in a patch touching the manual."

while IFS= read -r line; do
    grep -q "${line}" "${tmpdir}"/checkpatch-test-unaligned-nodes-patch.log || \
    fail "failed to detect unaligned node in a patch touching the manual."
done < tests/checkpatch-test-unaligned-nodes-patch.ref

echo "[ OK ] detected unaligned nodes in a patch touching the manual."

# This checks the manual file extracted from the "Add a minimal GNU Boot
# manual." commit which adds unaligned nodes.
git show \
    "$(git ls-tree 08b9e449e94e99c0ec924e2026dc650b63ddc3e5 -- \
       manual/gnuboot.texi | awk '{print $3}')" \
    > "${tmpdir}"/gnuboot.texi

./scripts/checkpatch.scm \
    -f \
    "${tmpdir}"/gnuboot.texi > \
    "${tmpdir}"/checkpatch-test-unaligned-nodes-file.log 2>/dev/null || \
    fail "checkpatch.scm failed " \
         "when trying to detect unaligned node in the manual file."

while IFS= read -r line; do
    grep -q "${line}" "${tmpdir}"/checkpatch-test-unaligned-nodes-file.log || \
    fail "failed to detect unaligned node in the manual file."
done < tests/checkpatch-test-unaligned-nodes-file.ref

echo "[ OK ] detected unaligned nodes in the manual file."

# This checks the "manual: Describe the GNU Boot project." patch
# which doesn't add any unaligned nodes.
./scripts/checkpatch.scm \
    "$(git format-patch -1 5303fab6a49796d69fc9176b715409f925d8f608)" > \
    "${tmpdir}"/checkpatch-test-non-modified-unaligned-nodes-patch.log \
    2>/dev/null || \
    fail "checkpatch.scm failed " \
         "when checking non-modified unaligned nodes " \
         "in a patch touching the manual."

while IFS= read -r line; do
    grep -q -L "${line}" \
         "${tmpdir}"/checkpatch-test-non-modified-unaligned-nodes-patch.log
done < tests/checkpatch-test-non-modified-unaligned-nodes-patch.ref && \
    fail "warned against non-modified unaligned nodes " \
         "in a patch touching the manual."

echo "[ OK ] didn't warn against non-modified unaligned nodes" \
     "in a patch touching the manual."

# This checks the manual file extracted from the "manual: align nodes and
# require it too." commit which doesn't add any unaligned nodes.
git show \
    "$(git ls-tree 3cfb105dbc9dff5040be5ef461e14c6c1f8dace3 -- \
       manual/gnuboot.texi | awk '{print $3}')" \
    > "${tmpdir}"/gnuboot.texi

./scripts/checkpatch.scm \
    -f \
    "${tmpdir}"/gnuboot.texi > \
    "${tmpdir}"/checkpatch-test-non-modified-unaligned-nodes-file.log \
    2>/dev/null || \
    fail "checkpatch.scm failed" \
         "when checking non-modified unaligned nodes" \
         "in the manual file"

while IFS= read -r line; do
    grep -q -L "${line}" \
         "${tmpdir}"/checkpatch-test-non-modified-unaligned-nodes-file.log
done < tests/checkpatch-test-non-modified-unaligned-nodes-file.ref && \
    fail "warned against non-modified unaligned nodes" \
         "in the manual file"

echo "[ OK ] didn't warn against non-modified unaligned nodes" \
     "in the manual file."

################################################################################
# Test if checkpatch.scm correctly finds missing Spanish translation.          #
################################################################################

# This checks the "website: status: RC4/RC5: cosmetics: align cell
# text top-left." commit where website/pages/status.es.md exists, but
# the commit only updates website/pages/status.md.
./scripts/checkpatch.scm \
    "$(git format-patch -1 4c46963c3dd2a9f26fb48363a5b7c8395be61f5a)" > \
    "${tmpdir}"/checkpatch-test-missing-spanish-translation.log 2>/dev/null

while IFS= read -r line; do
    grep -q "${line}" "${tmpdir}"/checkpatch-test-missing-spanish-translation.log
done < tests/checkpatch-test-missing-spanish-translation.ref || \
    fail "failed to detect missing spanish translation in the website."

echo "[ OK ] detected missing spanish translation in the website."

# This checks the "website: status: 0.1 RC4: mark Vikings D16 as
# tested" commit where the Spanish translation is correctly updated.
./scripts/checkpatch.scm \
    "$(git format-patch -1 1f07a190bab3fb06c6adca70d72355a149ee09b3)" > \
    "${tmpdir}"/checkpatch-test-updated-spanish-translation.log 2>/dev/null

while IFS= read -r line; do
    ! grep -q "${line}" "${tmpdir}"/checkpatch-test-updated-spanish-translation.log
done < tests/checkpatch-test-missing-spanish-translation.ref || \
    fail "failed to indentify updated spanish translation in the website."

echo "[ OK ] identified updated spanish translation in the website."

################################################################################
# Test if checkpatch.scm correctly finds non-aligned markdown tables columns   #
################################################################################

./scripts/checkpatch.scm \
    -f tests/checkpatch-test-bad-tables.md > \
    "${tmpdir}"/checkpatch-test-bad-tables.log 2>/dev/null || \
    fail "checkpatch.scm failed " \
         "when trying to detect unaligned columns inside tables in a markdown file."

while IFS= read -r line; do
    grep -q "${line}" "${tmpdir}"/checkpatch-test-bad-tables.log || \
    fail "failed to detect unaligned columns inside tables in a markdown file."
done < tests/checkpatch-test-bad-tables.ref

echo "[ OK ] detected unaligned columns inside tables in a markdown file."

# This checks the manual file extracted from the "website: status: clarify
# what kind of T60 are supported." commit which has no unaligned tables.
git show \
    "$(git ls-tree 5a4ea74643d1014d420d01a59de0d89d50847d8f -- \
       website/pages/status.md | awk '{print $3}')" \
    > "${tmpdir}"/status.md

./scripts/checkpatch.scm \
    -f \
    "${tmpdir}"/status.md > \
    "${tmpdir}"/checkpatch-test-good-tables.log 2>/dev/null || \
    fail "checkpatch.scm failed " \
         "when trying to detect unaligned columns inside tables in a markdown file."

while IFS= read -r line; do
    grep -q -L "${line}" \
         "${tmpdir}"/checkpatch-test-good-tables.log
done < tests/checkpatch-test-bad-tables.ref && \
    fail "warned against aligned columns inside tables in a markdown file."

echo "[ OK ] didn't warn against aligned nodes in the manual file."

################################################################################
# Test checkpatch.scm with all the existing patches. It should not crash.      #
################################################################################

echo "[ .. ] Checking if any existing patch makes checkpatch.scm crash."

# The very first commit in GNU Booot
# (55760a644a8d38d9534906cadce6584a27370758 ("images from old
# Libreboot git repo: 149273c6742aeed14ec1aaca019f552cfb109457")) is
# huge: it is 19 MiB, and it takes a while to process, even with a
# KGPE-D16, so it is better to skip it.
patches="$("${topdir}"/resources/wrapper/git format-patch \
    639f71f6e92407aafa03d7c364215c2f162367e1 -o "${tmpdir}")"

# shellcheck disable=SC2086
"${topdir}"/scripts/checkpatch.scm ${patches} | sed 's#^#       #g' || \
    fail "checkpatch.scm crashed."

echo "[ OK ] None of the existing patches make checkpatch.scm crash."

################################################################################
# Cleanups and end                                                             #
################################################################################

rm -rf "${tmpdir}"

printf "+---------------------+\n"
printf "| Running tests done: |\n"
printf "+---------------------+\n"
