#!/usr/bin/env bash
#
# Copyright (C) 2023,2024 Denis 'GNUtoo' Carikli <GNUtoo@cyberdimension.org>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

set -e

fail()
{
    # shellcheck disable=SC2124
    message="$@"

    printf "[ !! ] scripts/checkpatch.scm test failed: %s\n" \
           "${message}"

    exit 1
}

################################################################################
# Setup                                                                        #
################################################################################

printf "+--------------------------------------+\n"
printf "| Running scripts/checkpatch.scm test: |\n"
printf "+--------------------------------------+\n"

topdir="$(dirname "$(dirname "$(realpath "$0")")")"
tmpdir="$(mktemp -d)"

test -f "${topdir}"/scripts/checkpatch.scm || fail "checkpatch.scm not found."
test -f "${topdir}"/resources/git/git || fail "resources/git/git not found."

################################################################################
# Test if checkpatch.scm correctly finds non-aligned nodes.                    #
################################################################################

# This checks the "Add a minimal GNU Boot manual." commit which has
# unaligned nodes.
./scripts/checkpatch.scm \
    "$(git format-patch -1 08b9e449e94e99c0ec924e2026dc650b63ddc3e5)" > \
    "${tmpdir}"/checkpatch-test-unaligned-nodes.log 2>/dev/null || \
    fail "checkpatch.scm failed " \
         "when trying to detect unaligned node in the manual."

while IFS= read -r line; do
    grep -q "${line}" "${tmpdir}"/checkpatch-test-unaligned-nodes.log || \
    fail "failed to detect unaligned node in the manual."
done < tests/checkpatch-test-unaligned-nodes.ref || \

echo "[ OK ] detected unaligned nodes in the manual."

# This checks the "manual: Describe the GNU Boot project." commit
# which has non-modified unaligned nodes.
./scripts/checkpatch.scm \
    "$(git format-patch -1 5303fab6a49796d69fc9176b715409f925d8f608)" > \
    "${tmpdir}"/checkpatch-test-non-modified-unaligned-nodes.log \
    2>/dev/null || \
    fail "checkpatch.scm failed " \
         "when checking non-modified unaligned nodes in the manual."

while IFS= read -r line; do
    grep -q -L "${line}" \
         "${tmpdir}"/checkpatch-test-non-modified-unaligned-nodes.log
done < tests/checkpatch-test-non-modified-unaligned-nodes.ref && \
    fail "warned against non-modified unaligned nodes in the manual."

echo "[ OK ] didn't warn against non-modified unaligned nodes in the manual."

################################################################################
# Test checkpatch.scm with all the existing patches. It should not crash.      #
################################################################################

echo "[ .. ] Checking if any existing patch makes checkpatch.scm crash."

# The very first commit in GNU Booot
# (55760a644a8d38d9534906cadce6584a27370758 ("images from old
# Libreboot git repo: 149273c6742aeed14ec1aaca019f552cfb109457")) is
# huge: it is 19 MiB, and it takes a while to process, even with a
# KGPE-D16, so it is better to skip it.
patches="$("${topdir}"/resources/git/git format-patch \
    639f71f6e92407aafa03d7c364215c2f162367e1 -o "${tmpdir}")"

# shellcheck disable=SC2086
"${topdir}"/scripts/checkpatch.scm ${patches} | sed 's#^#       #g' || \
    fail "checkpatch.scm crashed."

echo "[ OK ] None of the existing patches make checkpatch.scm crash."

################################################################################
# Cleanups and end                                                             #
################################################################################

rm -rf "${tmpdir}"

printf "+---------------------+\n"
printf "| Running tests done: |\n"
printf "+---------------------+\n"
