#!/usr/bin/env bash
#
# Various code quality tests to avoid regressions in code quality.
#
# Copyright (C) 2023,2024 Denis 'GNUtoo' Carikli <GNUtoo@cyberdimension.org>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

report()
{
    ret=$?
    path="$1"
    test="$2"

    message="${path}"

    if [ ${ret} -eq 0 ] ; then
	echo "[ OK ] ${message}"
    else
	message="${path}: ${test} test"
	echo "[ !! ] ${message} failed."
	exit ${ret}
    fi
}

run_shellcheck()
{
    for path in "$@" ; do
	head -n1 "${path}" | grep -q '^#!/usr/bin/env bash$' || \
	    report "${path}" "\"#!/usr/bin/env bash\""
	shellcheck -s bash -x "${path}" ; report "${path}"
    done
}

run_grub_script_check()
{
    for path in "$@" ; do
	grub-script-check  "${path}" ; report "${path}"
    done
}

run_markdown_check()
{
    for path in "$@" ; do
	scripts/checkpatch.scm -f  "${path}" ; report "${path}"
    done
}

printf "+---------------------------+\n"
printf "| Running shellcheck tests: |\n"
printf "+---------------------------+\n"
run_shellcheck \
    autogen.sh \
    build \
    download \
    guix-revision.sh \
    modify \
    update \
    manual/build-guix-i686-linux.sh.in \
    manual/build-guix-x86_64-linux.sh.in \
    resources/packages/coreboot/distclean \
    resources/packages/dependencies/install \
    resources/packages/descriptors/distclean \
    resources/packages/grub/distclean \
    resources/packages/i945-thinkpads-install-utilities/clean \
    resources/packages/i945-thinkpads-install-utilities/distclean \
    resources/packages/i945-thinkpads-install-utilities/download \
    resources/packages/i945-thinkpads-install-utilities/module \
    resources/packages/manual/clean \
    resources/packages/manual/distclean \
    resources/packages/manual/test \
    resources/packages/memtest86plus/distclean \
    resources/packages/payloads/distclean \
    resources/packages/release/test \
    resources/packages/rom_images/distclean \
    resources/packages/roms/distclean \
    resources/packages/roms/download \
    resources/packages/roms/test \
    resources/packages/seabios/distclean \
    resources/packages/src/distclean \
    resources/packages/u-boot-libre/distclean \
    resources/packages/website/distclean \
    resources/scripts/misc/guix.sh \
    resources/scripts/tasks/distclean.sh \
    tests/checkpatch \
    tests/distclean \
    tests/lint \
    website/build.sh \
    website/check.sh \
    website/serve.sh

# For now we only check markdown tables. This is why we only have markdown
# files with tables below.
run_markdown_check \
    website/pages/docs/build/index.md \
    website/pages/docs/history/index.md \
    website/pages/status.es.md \
    website/pages/status.md

printf "+----------------------------------+\n"
printf "| Running grub-script-check tests: |\n"
printf "+----------------------------------+\n"
run_grub_script_check \
    resources/grub/config/grub.cfg

printf "+---------------------+\n"
printf "| Lint tests done     |\n"
printf "+---------------------+\n"
