#!/usr/bin/env bash
#
# Copyright (C) 2026 Denis 'GNUtoo' Carikli <GNUtoo@cyberdimension.org>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

# This is required to make the "${cmd//+([[:space:]])/ }" work. And
# the "${cmd//+([[:space:]])/ }" is required to make shellcheck happy:
# sed works fine but shellcheck complains, and I didn't find a way to
# remove the complaint as '# shellcheck disable=SC2124' needs to be
# right before the statement with sed, but that statement ends up
# several lines below the printf. See "3.5.8.1 Pattern Matching" in
# the bash info manual for more details.
shopt -s extglob

topdir="$(realpath "$(dirname "$(dirname "$(dirname "$(realpath "$0")")")")")"

# We need ${GUIX_REVISION}
eval "$("${topdir}"/guix-revision.sh print-shell)"

source "${topdir}"/resources/scripts/misc/sysexits.sh

# We need ${GUIX_BUILD_MAX_CORES}
if [ ! -f "${topdir}"/config.sh ] ; then
    echo "config.sh not found in GNU Boot top directory (""${topdir}"")"
    echo "To fix it run the following commands:"
    echo "    cd ""${topdir}"""
    echo "    ./autogen.sh"
    echo "    ./configure"
    exit "${EX_NOINPUT}"
fi
source "${topdir}"/config.sh

# We need -C resources/wrapper/channels.scm to make sure to only use
# the default channels provided by Guix.
guix_wrapper()
{
    # shellcheck disable=SC2124
    cmd="guix time-machine \
          -C ""${topdir}""/resources/wrapper/channels.scm \
         --commit=${GUIX_REVISION} \
         -- $@"

    printf "$0: '%s' => '%s'\n" \
           "$0 $*" \
           "${cmd//+([[:space:]])/ }" \
           > /dev/stderr
    ${cmd}
}

if [ "$#" -eq 1 ] && [ "$1" == "-h" ] ; then
    guix_wrapper -h
elif [ "$#" -eq 1 ] && [ "$1" == "--help" ] ; then
    guix_wrapper --help
elif [ "$#" -eq 1 ] && [ "$1" == "-V" ] ; then
    guix_wrapper -V
elif [ "$#" -eq 1 ] && [ "$1" == "--version" ] ; then
    guix_wrapper --version
elif [ "$#" -gt 1 ] ; then
    command="$1"
    shift 1

    case "${command}" in
	# The commands below support -L arguments.
        "edit")
            ;&
        "graph")
            ;&
        "lint")
            ;&
        "refresh")
            ;&
        "repl")
            ;&
        "search")
            ;&
        "show")
            ;&
        "size")
            ;&
        "style")
	    guix_wrapper \
                "${command}" \
                -L "${topdir}"/resources/guix/ \
                -L "${topdir}"/resources/guix/gnuboot/patches/ \
                "$@"
            ;;
	# The commands below support -L and --cores=NUM arguments.
	"archive")
            ;&
        "build")
            ;&
        "copy")
            ;&
        "deploy")
            ;&
        "environment")
            ;&
        "home")
            ;&
        "install")
            ;&
        "pack")
            ;&
        "package")
            ;&
        "pull")
            ;&
        "remove")
            ;&
        "shell")
            ;&
        "system")
            ;&
        "upgrade")
            guix_wrapper \
                "${command}" \
		--cores=${GUIX_BUILD_MAX_CORES} \
                -L "${topdir}"/resources/guix/ \
                -L "${topdir}"/resources/guix/gnuboot/patches/ \
                "$@"
            ;;
	# The command below supports --cores but not -L.
        "time-machine")
            guix_wrapper "${command}" --cores=${GUIX_BUILD_MAX_CORES} "$@"
            ;;
	# The commands below support nor --cores nor -L.
        "challenge")
            ;&
        "container")
            ;&
        "describe")
            ;&
        "download")
            ;&
        "gc")
            ;&
        "git")
            ;&
        "hash")
            ;&
        "import")
            ;&
        "locate")
            ;&
        "offload")
            ;&
        "processes")
            ;&
        "publish")
            ;&
        "weather")
            guix_wrapper "${command}" "$@"
            ;;
        *)
            printf "%s: Error: unknown command %s.\n" \
                   "$0" \
                   "${command}"
            ;;
        esac
else
    guix_wrapper "$@"
fi
