#!/usr/bin/env bash
#
# Copyright (C) 2025 Denis 'GNUtoo' Carikli <GNUtoo@cyberdimension.org>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

# This is required to make the "${cmd//+([[:space:]])/ }" work. And
# the "${cmd//+([[:space:]])/ }" is required to make shellcheck happy:
# sed works fine but shellcheck complains, and I didn't find a way to
# remove the complaint as '# shellcheck disable=SC2124' needs to be
# right before the statement with sed, but that statement ends up
# several lines below the printf. See "3.5.8.1 Pattern Matching" in
# the bash info manual for more details.
shopt -s extglob

topdir="$(realpath "$(dirname "$(dirname "$(dirname "$0")")")")"

# We need ${GUIX_REVISION}
eval "$("${topdir}"/guix-revision.sh print-shell)"

# We need the --no-channel-files option, but it was only introduced in
# the Guix commit 9c8098424b5be3abf21144c74162ec39c0c2e799 ("pull,
# time-machine: Add '-q' to ignore channel files.") which is after
# Guix 1.4.0, so we first use time-machine without this option to get
# the option in the second time-machine.
guix_wrapper()
{
    # shellcheck disable=SC2124
    cmd="guix time-machine \
         --commit=9c8098424b5be3abf21144c74162ec39c0c2e799 \
         -- \
         time-machine --no-channel-files --commit=${GUIX_REVISION} \
         -- $@"

    printf "$0: '%s' => '%s'\n" \
           "$0 $*" \
           "${cmd//+([[:space:]])/ }" \
           > /dev/stderr
    ${cmd}
}

if [ "$#" -eq 1 ] && [ "$1" == "-h" ] ; then
    guix_wrapper -h
elif [ "$#" -eq 1 ] && [ "$1" == "--help" ] ; then
    guix_wrapper --help
elif [ "$#" -eq 1 ] && [ "$1" == "-V" ] ; then
    guix_wrapper -V
elif [ "$#" -eq 1 ] && [ "$1" == "--version" ] ; then
    guix_wrapper --version
elif [ "$#" -gt 1 ] ; then
    command="$1"
    shift 1

    # Some commands support -L, some other don't. This only need to
    # match the commands provided by Guix's ${GUIX_REVISION}.
    case "${command}" in
        "archive")
            ;&
        "build")
            ;&
        "copy")
            ;&
        "deploy")
            ;&
        "edit")
            ;&
        "environment")
            ;&
        "graph")
            ;&
        "home")
            ;&
        "install")
            ;&
        "lint")
            ;&
        "pack")
            ;&
        "package")
            ;&
        "pull")
            ;&
        "refresh")
            ;&
        "remove")
            ;&
        "repl")
            ;&
        "search")
            ;&
        "shell")
            ;&
        "show")
            ;&
        "size")
            ;&
        "style")
            ;&
        "system")
            ;&
        "time-machine")
            ;&
        "upgrade")
            guix_wrapper \
                "${command}" \
                -L "${topdir}"/resources/guix/ \
                -L "${topdir}"/resources/guix/gnuboot/patches/ \
                "$@"
            ;;
        "challenge")
            ;&
        "container")
            ;&
        "describe")
            ;&
        "download")
            ;&
        "gc")
            ;&
        "git")
            ;&
        "hash")
            ;&
        "import")
            ;&
        "locate")
            ;&
        "offload")
            ;&
        "processes")
            ;&
        "publish")
            ;&
        "weather")
            guix_wrapper "${command}" "$@"
            ;;
        *)
            printf "%s: Error: unknown command %s.\n" \
                   "$0" \
                   "${command}"
            ;;
        esac
else
    guix_wrapper "$@"
fi
