#!/usr/bin/env bash
#
# Copyright (C) 2025 Denis 'GNUtoo' Carikli <GNUtoo@cyberdimension.org>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

topdir="$(realpath "$(dirname "$(dirname "$(dirname "$0")")")")"

# We need ${GUIX_REVISION}
eval "$("${topdir}"/guix-revision.sh print-shell)"

guix="guix time-machine --no-channel-files --commit=${GUIX_REVISION} -- "

if [ "$#" -eq 1 ] && [ "$1" == "-h" ] ; then
    ${guix} -h
elif [ "$#" -eq 1 ] && [ "$1" == "--help" ] ; then
    ${guix} --help
elif [ "$#" -eq 1 ] && [ "$1" == "-V" ] ; then
    ${guix} -V
elif [ "$#" -eq 1 ] && [ "$1" == "--version" ] ; then
    ${guix} --version
elif [ "$#" -gt 1 ] ; then
    command="$1"
    shift 1

    # Some commands support -L, some other don't. This only need to
    # match the commands provided by Guix's ${GUIX_REVISION}.
    case "${command}" in
        "archive")
            ;&
        "build")
            ;&
        "copy")
            ;&
        "deploy")
            ;&
        "edit")
            ;&
        "environment")
            ;&
        "graph")
            ;&
        "home")
            ;&
        "install")
            ;&
        "lint")
            ;&
        "pack")
            ;&
        "package")
            ;&
        "pull")
            ;&
        "refresh")
            ;&
        "remove")
            ;&
        "repl")
            ;&
        "search")
            ;&
        "shell")
            ;&
        "show")
            ;&
        "size")
            ;&
        "style")
            ;&
        "system")
            ;&
        "time-machine")
            ;&
        "upgrade")
            ${guix} \
                "${command}" \
                -L "${topdir}"/resources/guix/ \
                -L "${topdir}"/resources/guix/gnuboot/patches/ \
                "$@"
            ;;
        "challenge")
            ;&
        "container")
            ;&
        "describe")
            ;&
        "download")
            ;&
        "gc")
            ;&
        "git")
            ;&
        "hash")
            ;&
        "import")
            ;&
        "locate")
            ;&
        "offload")
            ;&
        "processes")
            ;&
        "publish")
            ;&
        "weather")
            ${guix} "${command}" "$@"
            ;;
        *)
            printf "%s: Error: unknown command %s.\n" \
                   "$0" \
                   "${command}"
            ;;
        esac
else
    ${guix} "$@"
fi
