#!/usr/bin/env bash

# arch script: installs build dependencies for Arch Linux
#
#	Copyright (C) 2021 Melissa Goad <mszoopers@protonmail.com>
#
#    This program is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, either version 3 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with this program.  If not, see <http://www.gnu.org/licenses/>.
#

[ "x${DEBUG+set}" = 'xset' ] && set -v
set -u -e

if [ $EUID -ne 0 ]; then
   printf "This script must be run as root\n" 
   exit 1
fi

pacman -S --needed --noconfirm packagekit

# Duplications are intentional. Please do not re-factor.
#
# This is so that they can moved to separate scripts.
#

pkcon -y install wget

# For downloading source code
# ------------------------------------------------------------

pkcon -y install git

# For Tianocore and iPXE
# TODO: check whether this is the full list

pkcon -y install nasm perl-libwww python2 subversion

# For building source code:
# ------------------------------------------------------------

pkcon -y install base-devel

# for running the crostool script (to get mrc.bin file for t440p)
pkcon -y install sharutils curl parted e2fsprogs unzip

# for cross-compiling ARM binaries
pkcon -y install arm-none-eabi-gcc

# Memtest86+ build dependencies
# ------------------------------------------------------------

pkcon -y install base-devel python2

# i945-pwm build dependencies
# ------------------------------------------------------------

pkcon -y install base-devel perl

# Coreboot build dependencies (also requires build-essential and git)
# ------------------------------------------------------------

pkcon -y install ncurses doxygen acpica gdb flex bison base-devel git openssl gcc-ada

# GRUB build dependencies (also requires build-essential, bison and flex)
# ------------------------------------------------------------

pkcon -y install bdf-unifont autogen help2man base-devel bison flex ttf-dejavu texinfo rsync python libusb xz gawk device-mapper fuse2 gettext freetype2

# BucTS build dependencies (external script)
# ------------------------------------------------------------

pkcon -y install base-devel

# Flashrom build dependencies (also requires build-essential)
# ------------------------------------------------------------

pkcon -y install libpciaccess pciutils zlib libftdi base-devel libusb

# For running make check
# ----------------------
pacman -S --needed shellcheck # lint
pacman -S --needed awk git grep lzip make sed tar xz # u-boot-libre
