#!/usr/bin/env bash

# arch script: installs build dependencies for Arch Linux
#
# Copyright (C) 2014-2016,2020,2021 Leah Rowe <leah@libreboot.org>
# Copyright (C) 2015,2016 Klemens Nanni <klemens@posteo.de>
# Copyright (C) 2016 Arthur Heymans <arthur@aheymans.xyz>
# Copyright (C) 2020 Wei Mingzhi <whistler_wmz@users.sf.net>
# Copyright (C) 2021 madbehaviorus <mad.behaviorus@mailbox.org>
# Copyright (C) 2021 qeeg <mszoopers@protonmail.com>
# Copyright (C) 2021 Ron Nazarov <noisytoot@disroot.org>
# Copyright (C) 2023 Denis 'GNUtoo' Carikli <GNUtoo@cyberdimension.org>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#

[ "x${DEBUG+set}" = 'xset' ] && set -v
set -u -e

sentinel=""

to_install=""
install_packages()
{
    for package in $@ ; do
        if [ "${package}" = "$(packan -Qq "${package}")" ] ; then
            continue
        else
            to_install="${to_install} ${package}"
        fi
    done
}

if [ $EUID -ne 0 ]; then
    printf "This script must be run as root\n"
    exit 1
fi

# Duplications are intentional. Please do not re-factor.
#
# This is so that they can moved to separate scripts.
#

install_packages wget

# For downloading source code
# ------------------------------------------------------------

install_packages git

# For Tianocore and iPXE
# TODO: check whether this is the full list

install_packages \
    nasm \
    perl-libwww \
    python2 \
    subversion \
    "${sentinel}"

# For building source code:
# ------------------------------------------------------------

install_packages base-devel

# for running the crostool script (to get mrc.bin file for t440p)
install_packages \
    curl \
    e2fsprogs \
    parted \
    sharutils \
    unzip \
    "${sentinel}"

# for cross-compiling ARM binaries
install_packages arm-none-eabi-gcc

# Memtest86+ build dependencies
# ------------------------------------------------------------

install_packages \
    base-devel \
    python2 \
    "${sentinel}"

# i945-pwm build dependencies
# ------------------------------------------------------------

install_packages \
    base-devel \
    perl \
    "${sentinel}"

# Coreboot build dependencies (also requires build-essential and git)
# ------------------------------------------------------------

install_packages \
    acpica \
    base-devel \
    bison \
    doxygen \
    flex \
    gcc-ada \
    gdb \
    git \
    ncurses \
    openssl \
    "${sentinel}"

# GRUB build dependencies (also requires build-essential, bison and flex)
# ------------------------------------------------------------

install_packages \
    autogen \
    base-devel \
    bdf-unifont \
    bison \
    device-mapper \
    flex \
    freetype2 \
    fuse2 \
    gawk \
    gettext \
    help2man \
    libusb \
    python \
    rsync \
    texinfo \
    ttf-dejavu \
    xz \
    "${sentinel}"

# BucTS build dependencies (external script)
# ------------------------------------------------------------

install_packages base-devel

# Flashrom build dependencies (also requires build-essential)
# ------------------------------------------------------------

install_packages \
    base-devel \
    libftdi \
    libpciaccess \
    libusb \
    pciutils \
    zlib \
    "${sentinel}"

# For running make check
# ----------------------
install_packages shellcheck # lint

# u-boot-libre
install_packages \
    awk \
    git \
    grep \
    lzip \
    make \
    sed \
    tar \
    xz \
    "${sentinel}"

if [ -n "${to_install}" ] ; then
    pacman -S --needed --noconfirm packagekit
    pkcon -y --allow-reinstall ${to_install}
fi
