#!/bin/bash

# Fedora script: installs build dependencies for Fedora
#
#	Copyright (C) 2021 Melody Goad <mszoopers@protonmail.com>
#	Copyright (C) 2021 Wei Mingzhi <whistler@member.fsf.org>
#
#    This program is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, either version 3 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with this program.  If not, see <http://www.gnu.org/licenses/>.
#

[ "x${DEBUG+set}" = 'xset' ] && set -v
set -u -e

if [ $EUID -ne 0 ]; then
   printf "This script must be run as root\n"
   exit 1
fi

dnf -y install PackageKit

# Duplications are intentional. Please do not re-factor.
#
# This is so that they can moved to separate scripts.
#

pkcon -y --allow-reinstall install wget

# For downloading source code
# ------------------------------------------------------------

pkcon -y --allow-reinstall install git

# For building the documentation
# ------------------------------------------------------------

pkcon -y --allow-reinstall install pandoc

# For Tianocore and iPXE
# TODO: check whether this is the full list

pkcon -y --allow-reinstall install nasm perl-libwww-perl python2 subversion

# For building source code:
# ------------------------------------------------------------

pkcon -y --allow-reinstall install gcc libtool

# for running the crostool script (to get mrc.bin file for t440p)
pkcon -y --allow-reinstall install sharutils curl parted e2fsprogs unzip

# for cross-compiling ARM binaries
pkcon -y --allow-reinstall install arm-none-eabi-gcc-cs

# Memtest86+ build dependencies
# ------------------------------------------------------------

pkcon -y --allow-reinstall install gcc python2

# i945-pwm build dependencies
# ------------------------------------------------------------

pkcon -y --allow-reinstall install gcc perl

# Coreboot build dependencies (also requires build-essential and git)
# ------------------------------------------------------------

pkcon -y --allow-reinstall install gcc-gnat ncurses-devel doxygen acpica-tools gdb flex bison gcc git openssl-devel gprbuild bzip2

# GRUB build dependencies (also requires build-essential, bison and flex)
# ------------------------------------------------------------

pkcon -y --allow-reinstall install unifont-fonts autogen help2man gcc bison flex dejavu-fonts-all texinfo rsync python libusb xz gawk device-mapper fuse gettext freetype-devel intltool libselinux-devel

# BucTS build dependencies (external script)
# ------------------------------------------------------------

pkcon -y --allow-reinstall install gcc

# Flashrom build dependencies (also requires build-essential)
# ------------------------------------------------------------

pkcon -y --allow-reinstall install pciutils-devel zlib-devel libftdi-devel gcc libusb-devel

# For running make check
# ----------------------
pkcon -y --allow-reinstall install ShellCheck # lint
pkcon -y --allow-reinstall install gawk git grep lzip make sed tar xz # u-boot-libre
