#!/bin/sh
#
# Copyright (C) 2023 Denis 'GNUtoo' Carikli <GNUtoo@cyberdimension.org>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

. "$(dirname $0)"/../scripts/misc/guix.sh
. "$(dirname $0)"/../scripts/misc/sysexits.sh

progname="resources/packages/dependencies/install"
true=0
false=1

usage()
{
    progname="$1"

    printf "Usage:\n"
    printf "\t%s --help\n" \ "${progname}"
    printf "\t%s # Setup Guix for usage for GNU Boot\n" \ "${progname}"
}

if [ $# -eq 1 ] && [ "$1" == "--help" ] ; then
    usage "${progname}"
    exit 0
elif [ $# -eq 0 ] ; then
    update_guix_to_latest_release
else
    usage "${progname}"
    exit ${EX_USAGE}
fi
