#!/usr/bin/env bash

# trisquel script: installs build dependencies for PureOS 10, Trisquel
# 9 and Trisquel 10.
#
# Copyright (C) 2014-2016,2020-2021 Leah Rowe <leah@libreboot.org>
# Copyright (C) 2015,2016 Klemens Nanni <klemens@posteo.de>
# Copyright (C) 2016 Arthur Heymans <arthur@aheymans.xyz>
# Copyright (C) 2020 Wei Mingzhi <whistler_wmz@users.sf.net>
# Copyright (C) 2021 madbehaviorus <mad.behaviorus@mailbox.org>
# Copyright (C) 2021 qeeg <mszoopers@protonmail.com>
# Copyright (C) 2021 Ron Nazarov <noisytoot@disroot.org>
# Copyright (C) 2023, Adrien Bourmault <neox@gnu.org>
# Copyright (C) 2023-2025 Denis 'GNUtoo' Carikli <GNUtoo@cyberdimension.org>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#

[ "x${DEBUG+set}" = 'xset' ] && set -v
set -u -e

sentinel=""

to_install=""
install_packages()
{
    for package in $@ ; do
        if dpkg -l "${package}" | grep "^ii" 2>&1>/dev/null ; then
            continue
        else
            to_install="${to_install} ${package}"
        fi
    done
}

if [ $EUID -ne 0 ]; then
    printf "This script must be run as root\n"
    exit 1
fi

# Duplications are intentional. Please do not re-factor.
#
# This is so that they can moved to separate scripts.
#

install_packages wget

# For downloading source code
# ------------------------------------------------------------

install_packages git

# For Tianocore and iPXE
# TODO: check whether this is the full list

install_packages \
    nasm \
    uuid-dev \
    "${sentinel}"

# For building source code:
# ------------------------------------------------------------

install_packages build-essential

# for running the crostool script (to get mrc.bin file for t440p)
install_packages \
    curl \
    e2fsprogs \
    parted \
    sharutils \
    unzip \
    "${sentinel}"

# to use the right software versions and links for compiling
install_packages \
    libtool \
    pkg-config \
    "${sentinel}"

# for cross-compiling ARM binaries
install_packages gcc-arm-linux-gnueabi

[ "$(uname -i)" = x86_64 ] || [ "$(uname -m)" = x86_64 ]
arch=${?}

# For cross-compiling i686 target on x86_64 host.
if [ "${arch}" -eq 0 ]; then
    install_packages \
	lib32z1-dev \
        dh-autoreconf \
        g++-multilib \
        gcc-multilib \
        lib32stdc++6 \
        libc6-dev-i386 \
        libc6-i386 \
        "${sentinel}"
fi

# Memtest86+ build dependencies
# ------------------------------------------------------------

install_packages \
    build-essential \
    python-is-python3 \
    python2.7 \
    "${sentinel}"

# i945-pwm build dependencies
# ------------------------------------------------------------

install_packages \
    build-essential \
    perl \
    "${sentinel}"

# Coreboot build dependencies (also requires build-essential and git)
# ------------------------------------------------------------

install_packages \
    acpica-tools \
    bison \
    build-essential \
    doxygen \
    flex \
    gdb \
    git \
    gnat \
    libncurses5-dev \
    libssl-dev \
    "${sentinel}"

# GRUB build dependencies (also requires build-essential, bison and flex)
# ------------------------------------------------------------

install_packages \
    autoconf \
    autogen \
    automake \
    autotools-dev \
    bison \
    build-essential \
    flex \
    gawk \
    help2man \
    libdevmapper-dev \
    libfont-freetype-perl \
    libfreetype6-dev \
    libfuse-dev \
    liblzma-dev \
    libopts25 \
    libopts25-dev \
    libselinux1-dev \
    libtool \
    libtool-bin \
    m4 \
    "${sentinel}"

# BucTS build dependencies (external script)
# ------------------------------------------------------------

install_packages build-essential

# Flashrom build dependencies (also requires build-essential)
# ------------------------------------------------------------

install_packages \
    build-essential \
    libftdi-dev \
    libpci-dev \
    libusb-1.0-0 \
    libusb-1.0-0-dev \
    libusb-dev \
    pciutils \
    zlib1g-dev \
    "${sentinel}"

# For running make check
# ----------------------
install_packages shellcheck # lint

# u-boot-libre
install_packages \
    gawk \
    git \
    grep \
    lzip \
    make \
    sed \
    tar \
    xz-utils \
    "${sentinel}"

# For building the website tarball
install_packages \
    cvs \
    graphicsmagick \
    graphviz \
    pandoc \
    texinfo \
    texlive \
    texlive-plain-generic \
    "${sentinel}"

if [ -n "${to_install}" ] ; then
    apt install -y ${to_install}
fi
