;;; Copyright © 2015 David Thompson <davet@gnu.org>
;;; Copyright © 2016 Christine Lemmer-Webber <cwebber@dustycloud.org>
;;; Copyright © 2025 Denis 'GNUtoo' Carikli <GNUtoo@cyberdimension.org>
;;;
;;; This file is based on haunt/builder/blog.scm,
;;; haunt/reader/commonmark.scm and tests/post.scm and from Haunt
;;; 2.6.0.
;;;
;;; This file is free software; you can redistribute it and/or modify
;;; it under the terms of the GNU General Public License as published
;;; by the Free Software Foundation; either version 3 of the License,
;;; or (at your option) any later version.
;;;
;;; Haunt is distributed in the hope that it will be useful, but
;;; WITHOUT ANY WARRANTY; without even the implied warranty of
;;; MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
;;; General Public License for more details.
;;;
;;; You should have received a copy of the GNU General Public License
;;; along with Haunt.  If not, see <http://www.gnu.org/licenses/>.

(define-module (modules builders gnuboot)
  #:use-module (commonmark)
  #:use-module (haunt artifact)
  #:use-module (haunt builder assets)
  #:use-module (haunt html)
  #:use-module (haunt post)
  #:use-module (haunt site)
  #:use-module (haunt utils)
  #:use-module (ice-9 match)
  #:use-module (ice-9 popen)
  #:use-module (ice-9 regex)
  #:use-module (ice-9 rdelim)
  #:use-module (ice-9 string-fun)
  #:use-module (srfi srfi-1)
  #:use-module (srfi srfi-9)
  #:use-module (srfi srfi-19)
  #:export (gnuboot-website))

(define-record-type <theme>
  (make-theme name layout post-template collection-template)
  theme?
  (name theme-name)
  (layout theme-layout)
  (post-template theme-post-template)
  (collection-template theme-collection-template))

;; References (MDN):
;; https://developer.mozilla.org/docs/Web/HTML/Reference/Global_attributes/id
(define (title->anchor title)
  (fold
   (lambda (func s) (func s))
   title
   (list
    ;; The IDs generated by Pandoc were lowercase
    string-downcase
    ;; The IDs generated by Pandoc didn't contain any coma
    (lambda (s)
      (string-filter (lambda (c) (not (eq? c #\,))) s))
    ;; The IDs generated by Pandoc didn't contain any columns
    (lambda (s)
      (string-filter (lambda (c) (not (eq? c #\:))) s))
    ;; The IDs generated by Pandoc didn't contain any plus
    (lambda (s)
      (string-filter (lambda (c) (not (eq? c #\+))) s))
    ;; The IDs generated by Pandoc didn't contain any exclamation mark
    (lambda (s)
      (string-filter (lambda (c) (not (eq? c #\!))) s))
    ;; The IDs generated by Pandoc didn't contain any question mark
    (lambda (s)
      (string-filter (lambda (c) (not (eq? c #\?))) s))
    (lambda (s)
      (string-filter (lambda (c) (not (eq? c #\¿))) s))
    ;; The IDs generated by Pandoc didn't contain any slash
    (lambda (s)
      (string-filter (lambda (c) (not (eq? c #\/))) s))
    ;; The IDs generated by Pandoc didn't contain any quote
    (lambda (s)
      (string-filter (lambda (c) (not (eq? c #\'))) s))
    ;; The IDs generated by Pandoc didn't contain any parentesis
    (lambda (s)
      (string-filter (lambda (c) (not (eq? c #\())) s))
    (lambda (s)
      (string-filter (lambda (c) (not (eq? c #\)))) s))
    ;; An ID attribute's value must not contain ASCII whitespace
    ;; characters (MDN).
    (lambda (s)
      (string-replace-substring s " " "-")))))

(define (add-anchor tag body index)
  (define text
    (string-join (filter string? (car (list-tail body index))) ""))
  (define replacement
    `(div (@ (class "h"))
          (,tag (@ (id ,(title->anchor text))) ,text)
          (a (@ (aria-hidden "true")
                (href ,(string-append "#" (title->anchor text))))
             "[link]")))
  (set-car! (list-tail body index) replacement))

(define (modify-tag-elements tag body func)
  (define index (list-index (lambda (elm) (eq? (car elm) tag)) body))
  (if index
      ((lambda _
         (func tag body index)
         (modify-tag-elements tag (cdr (list-tail body index)) func)))))

(define (return-to-index post)
  (cond
   ((string=? "pages/index.md" (post-file-name post)) '())
   ((string=? "pages/index.es.md" (post-file-name post)) '())
   ((string=? "pages" (dirname (post-file-name post)))
    '(p
      (a (@ (href "./"))
         "Return to index")))
   (else
    '(p
      (a (@ (href "../"))
         "Return to previous index")))))

(define (gnuboot-layout site post body)
  (map (lambda (elm) (modify-tag-elements elm body add-anchor)) '(h1 h2 h3))

  (define (markdown-relative-url post)
     (regexp-substitute
      #f
      (string-match
       (string-append "^" (site-posts-directory site) "/")
       (post-file-name post)) 'post))

  (define (markdown-absolute-url post)
    (string-append
     "https://gnu.org/software/gnuboot/"
     (regexp-substitute
      #f
      (string-match
       (string-append "^" (site-posts-directory site) "/")
       (post-file-name post)) 'post)))

  (define (spanish-md-page? path)
    (if
     (string-match "\\.es.md$" path)
     #t
     #f))

  (define (english-md-page? path)
    (not (spanish-md-page? path)))

  (define (spanish-md-page site post)
    (define page-path (markdown-relative-url post))
    (if (spanish-md-page? page-path)
        page-path
        (regexp-substitute
         #f
         (string-match "\\.md$" page-path)
         'pre ".es.md")))

  (define (english-md-page site post)
    (define page-path (markdown-relative-url post))
    (if (english-md-page? page-path)
        page-path
        (regexp-substitute
         #f
         (string-match "\\.es\\.md$" page-path)
         'pre ".md")))

  (define (spanish-html-page site post)
    (define md-page-path (markdown-relative-url post))
    (if (spanish-md-page? md-page-path)
        (regexp-substitute
         #f
         (string-match "\\.md$" md-page-path)
         'pre ".html")
        (regexp-substitute
         #f
         (string-match "\\.md$" md-page-path)
         'pre ".es.html")))

  (define (english-html-page site post)
    (define md-page-path (markdown-relative-url post))
    (cond ((string=? md-page-path "index.md")
           "./")
          ((string=? md-page-path "index.es.md")
           "./")
           ((english-md-page? md-page-path)
            (regexp-substitute
             #f
             (string-match "\\.md$" md-page-path)
             'pre ".html"))
           (else
            (regexp-substitute
             #f
             (string-match "\\.es\\.md$" md-page-path)
             'pre ".html"))))

  (define (generate-language-links site post)
    (if
     (access?
      (string-append
     (site-posts-directory site) "/" (spanish-md-page site post))
    R_OK)
   `(p
     (a (@ (href ,(english-html-page site post))) "English")
     "|"
     (a (@ (href ,(spanish-html-page site post))) "Español"))
   ""))

  `((doctype "html")
    (html
     (@
      ,(if (spanish-md-page? (markdown-relative-url post))
           '(lang "es")
           '(lang "en"))
      ;; TODO: understand what that does.
      (dir "ltr"))
     (head
      (meta (@ (charset "utf-8")))
      (meta (@ (name "generator")
               (content "pandoc")))
      ;; TODO: Understand what it does
      (meta
       (@ (content "width=device-width, initial-scale=1.0, user-scalable=yes")
          (name "viewport")))
      (title ,(site-title site) " – " ,(string-append (post-ref post 'title)))
      (link (@ (rel "stylesheet") (href "/software/gnuboot/gnuboot.css")))
      ;; TODO: Only kept to minimize the diff with lbssg.
      (link (@ (rel "stylesheet") (href "")))
      ;; TODO: Only kept to minimize the diff with lbssg. The
      ;; generated HTML isn't exactly the same, so we workaround that
      ;; in build/haunt/fixup-feed-link.sh
      (link (@ (rel "alternate")
               (href "feed.xml")
               (title "RSS Feed")
               (type "application/rss+xml"))))
     (body
      (div
       (@ (class "page"))
       (header
        (div
         (@ (class "title"))
         (h1
          (@ (class "title"))
          ,(post-ref post 'title)))
        (div (@ (class "menu"))
             (ul
              (li (a (@ (href "/software/gnuboot/index.html"))
                     "Home"))
              (li (a (@ (href "/software/gnuboot/status.html"))
                     "Status"))
              (li (a (@ (href "/software/gnuboot/docs/install/"))
                     "Get GNU Boot"))
              (li (a (@ (href "/software/gnuboot/docs/"))
                     "Docs"))
              (li (a (@ (href "/software/gnuboot/news.html"))
                     "News"))
              (li (a (@ (href "https://savannah.gnu.org/bugs/?group=gnuboot"))
                     "Bugs"))
              (li (a (@ (href "https://savannah.gnu.org/projects/gnuboot/"))
                     "Savannah forge"))
              (li (a (@ (href "/software/gnuboot/contribute.html"))
                     "Helping GNU Boot"))
              (li (a (@ (href "/software/gnuboot/contact.html"))
                     "Contact"))))
        ;; TODO: Only kept to minimize the diff with lbssg. The
        ;; generated HTML isn't identic to lbssg, so the version
        ;; generated by lbssg is fixed by
        ;; build/lbssg/fixup-comments.sh
        (!-- (@ (class "menu")) "")
        (hr)
        ,(if
          (post-ref post 'x-unreviewed)
          '(div
            (@ (class "warning_banner"))
            (p
             "The information on this page have one or more of these issues:"
             (ul
              (li
               "It could lack any safety warnings for handling substances
      dangerous for Health. This is because some articles expects the
      readers to either be (self) trained professional in electronics
      repairs and know about how to handle these substances, or to not
      attempt anythings that requires these skills themselves.")

              (li "It could lack background information or pointers to information
      that explains how to not break computers. So far this only
      applies to some articles that explain how to disassemble
      computers and/or to modify modify the computers electronic
      circuits: some of them expect the readers to either be (self)
      trained professional in electronics repairs and know about how
      to properly understand some advices to not break the electronic
      circuit.")

              (li "It could be outdated.")
              (li "It could refer to other boot software related projects instead
    of GNU Boot."))

             "We also need help (ideally in the form of patches sent to the GNU
  Boot mailing list) to fix this website. See
  the "
             (a (@ (href "/software/gnuboot/git.html")) "Helping GNU Boot")
             "page for more details on how to contribute to GNU Boot.")
            (hr))
          ""))
       ,(generate-language-links site post)
       ,(return-to-index post)
       ,body
       (div
        (@ (id "footer"))
        (hr)
        (ul
         (li (a (@ (href "/software/gnuboot/contribute.html"))
                "Edit this page"))
         (li (a (@ (href "/software/gnuboot/license.html"))
                "License"))
         (li (a (@ (href "/software/gnuboot/template-license.html"))
                "Template"))
         (li (a (@ (href "/software/gnuboot/logo-license.html"))
                "Logo")))
        (hr)
        ;; TODO: This is obviously kept for minimizing the diff with
        ;; the old website, ideally up to the point where we generate
        ;; the exact same HTML. Once the comparison is done, we can
        ;; safely change the text below to tell that we use Haunt.
        (p "This page was generated with "
           (a (@ (href "https://libreboot.org/docs/sitegen")) "lbssg")
           " from the commit "
           ,(let* ((port
                    (open-input-pipe
                     (string-append
                      "git --no-pager log --oneline HEAD -1 --format="
                      "'%h (“%s”).'")))
                   (str (read-line port)))
              (close-pipe port) str)))

       (p
        ,(if (spanish-md-page? (markdown-relative-url post))
             "Fichero Markdown para esta página: "
             "Markdown file for this page: "
             )
          (a (@ (class "uri")
                (href ,(markdown-absolute-url post)))
             ,(markdown-absolute-url post))))))))

(define (gnuboot-collection-template site title posts prefix)
  (define (post-uri post)
    (string-append (or prefix "") "/"
                   (site-post-slug site post) ".html"))
  `((h3 ,title)
    (ul
     ,@(map (lambda (post)
              `(li
                (a (@ (href ,(post-uri post)))
                   ,(post-ref post 'title))))
            posts))))

(define* (theme #:key
                (name "GNU Boot")
                (layout gnuboot-layout)
                (post-template post-sxml)
                (collection-template gnuboot-collection-template))
  (make-theme name layout post-template collection-template))

(define (with-layout theme site post body)
  ((theme-layout theme) site post body))

(define (render-post theme site post)
  (let ((body ((theme-post-template theme) post)))
    (with-layout theme site post body)))

(define (render-collection theme site title posts prefix)
  (let ((body ((theme-collection-template theme) site title posts prefix)))
    (with-layout theme site title body)))

(define gnuboot-theme
  (theme #:name "GNU Boot"
         #:layout gnuboot-layout
         #:post-template post-sxml
         #:collection-template gnuboot-collection-template))

(define* (gnuboot-website #:key prefix)
  "Return a procedure that transforms a list of posts into pages
decorated by THEME, whose URLs start with PREFIX."
  (define (make-file-name base-name)
    (if prefix
        (string-append prefix "/" base-name)
        base-name))

  (define (remove-html-extension string)
    (string-append
     (string-join
      (drop-right ;; remove .html
       (string-split
        string #\.)
       1)
      ".")
     ".html"))

  (define (remove-pages-prefix string)
    (string-join (cdr (string-split string #\/)) "/"))

  (lambda (site posts)
    (define (post->page post)
      (let
          ((base-name
            (remove-pages-prefix
             (remove-html-extension (post-file-name post)))))
        (serialized-artifact (make-file-name base-name)
                             (render-post gnuboot-theme site post)
                             sxml->html)))

    (define collection->page
      (match-lambda
        ((title file-name filter)
         (serialized-artifact
          (make-file-name file-name)
          (render-collection gnuboot-theme site title (filter posts) prefix)
          sxml->html))))

    (append (map post->page posts))))
