;;; Copyright © 2025 Denis 'GNUtoo' Carikli <GNUtoo@cyberdimension.org>
;;;
;;; This file is part of GNU Boot.
;;;
;;; GNU Boot is free software; you can redistribute it and/or modify it
;;; under the terms of the GNU General Public License as published by
;;; the Free Software Foundation; either version 3 of the License, or (at
;;; your option) any later version.
;;;
;;; GNU Bootx is distributed in the hope that it will be useful, but
;;; WITHOUT ANY WARRANTY; without even the implied warranty of
;;; MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
;;; General Public License for more details.
;;;
;;; You should have received a copy of the GNU General Public License
;;; along with GNU Boot.  If not, see <http://www.gnu.org/licenses/>.

(define-module (gnuboot packages build-utilities)
  #:use-module (gnu packages bison)
  #:use-module (gnu packages flex)
  #:use-module (guix build-system gnu)
  #:use-module (guix gexp)
  #:use-module (guix git-download)
  #:use-module ((guix licenses)
                #:prefix license:)
  #:use-module (guix packages)
  #:use-module (guix utils))

;; The bincfg package was added to Guix in the commit
;; fe8599a6bef6b86d58b6cefa107dd476597f5156 ("gnu: Add bincfg."), so
;; after the Guix 1.5.0 release.
(define-public bincfg
  (package
    (name "bincfg")
    (version "25.09")
    (source
     (origin
       (method git-fetch)
       (uri (git-reference
              (url "https://review.coreboot.org/coreboot")
              (commit version)))
       (file-name (git-file-name name version))
       (sha256
        (base32
         "1a1n64dwr5fzdnaj45bjci85ap5yra5gwz4x056zn6481xwvbsmv"))))
    (build-system gnu-build-system)
    (native-inputs (list bison flex))
    (arguments
     (list
      #:make-flags
      #~(list
         (string-append "CC=" #$(cc-for-target)))
      #:phases
      #~(modify-phases %standard-phases
          (delete 'configure) ; no configure script
          (add-after 'unpack 'chdir
            (lambda _
              (chdir "util/bincfg")))
          ;; (add-after 'build 'build-binaries
          ;;   (lambda* (#:key make-flags #:allow-other-keys)
          ;;     ;; generate GbE for X200
          ;;     (apply invoke "make" "gen-gbe-ich9m" make-flags)
          ;;     (copy-file "flashregion_3_gbe.bin" "gbe-ich9m.bin")
          ;;     (delete-file "flashregion_3_gbe.bin")
          ;;     ;; generate GbE for X220/x230
          ;;     (apply invoke "make" "gen-gbe-82579LM" make-flags)
          ;;     (copy-file "flashregion_3_gbe.bin" "gbe-82579LM.bin")
          ;;     (delete-file "flashregion_3_gbe.bin")
          ;;     ;; generate IFD for X200
          ;;     (apply invoke "make" "gen-ifd-x200" make-flags)
          ;;     (copy-file "flashregion_0_fd.bin" "ifd-x200.bin")
          ;;     (delete-file "flashregion_0_fd.bin")))
          ;; The Makefile has no install target.
          (replace 'install
            (lambda _
              (let ((bin (string-append #$output "/bin"))
                    (lib (string-append #$output "/lib/bincfg"))
                    (data (string-append #$output "/share/bincfg")))
                ;; Install the program
                (install-file "bincfg" bin)

                ;; And its data
                (for-each
                 (lambda (path)
                   (install-file path data))
                 (append (find-files "." ".*\\.set")
                         (find-files "." ".*\\.spec")))

                ;; And the files generated with the data
                (for-each
                 (lambda (path)
                   (install-file path lib))
                 (find-files "." ".*\\.bin"))))))
      #:tests? #f)) ; no test suite
    (home-page "https://coreboot.org")
    (synopsis "Encoder/decoder for binary formats defined in specification
files")
    (description "
The bincfg program comes with specifications files for the following binary
formats:
@itemize
@item Various DDR3 and DDR4 SPD
@item Configuration data for the Intel 82579LM Gigabit Ethernet PHY
@item Configuration data for the Intel Gigabit Ethernet controller present in
      the Intel ICH9-M chipset.
@item Intel Firmware Descriptor data for the Lenovo ThinkPad X200
@item Configuration data for the ITE IT8718F SuperIO
@end itemize
It also comes with example files generated by bincfg.")
    (license license:gpl3+)))

(define-public ich9utils
  (package
    (name "ich9utils")
    (version "0") ; There is only 1 commit so far.
    (source
     (origin
       (method git-fetch)
       (uri (git-reference
              (url "https://forge.a-lec.org/GNUBoot/ich9utils")
              (commit "53749b0c6f7c5778bdd1ec2b91cd230626752579")))
       (file-name (git-file-name "coreboot" version))
       (sha256
	(base32
	 "1sjzpc1gar0ry42h7h6jfgbcivs7840fqk4crrmw6l2236yi0wsn"))))
    (arguments
     (list
      #:tests? #f ; no tests
      #:phases
      #~(modify-phases %standard-phases
          (delete 'configure) ; there is only a Makefile
          (replace 'install
             (lambda* (#:key inputs #:allow-other-keys)
               (let ((bin (string-append #$output "/bin/")))
                 (install-file "demefactory" bin)
                 (install-file "ich9deblob" bin)
                 (install-file "ich9gen" bin)
                 (install-file "ich9show" bin)))))))
    (build-system gnu-build-system)
    (home-page "https://notabug.org/libreboot/ich9utils.git")
    (synopsis "Various tools that deal with the ICH9 Intel Flash Descriptor (IFD)")
    (description
     "The ich9utils package contains various utilities:
@itemize
@item demefactory: Disable ME firmware on GM45 boot flash, but leave
the ME region intact and enable read-write on all regions.
@item ich9deblob: Disable and remove the ME firmware from ICH9M / GM45 boot flash.
@item ich9gen: Generate deblobbed IFD and GBE 12KiB file.
@item ich9show: Show the ICH9 region read/write status.
@end itemize")
    (license license:gpl3+)))

(list bincfg
      ich9utils)
